In [16]:
import numpy as np

d = np.load('/data1/longshen/Datasets/Piano/POP909/piano_rolls/POP09-PIANOROLL-12-bin-quantization/001.npz')
list(d.keys())

['beat', 'chord', 'melody', 'bridge', 'piano']

In [2]:
d['melody'][0]

array([ 19,   0,   4,  19,   1,   4,  61, 115], dtype=int32)

In [3]:
d['melody'][1]

array([ 19,   1,   4,  19,   2,   4,  63, 109], dtype=int32)

In [18]:
beat = d['beat']
pr = np.zeros((3, len(beat)*12, 128, 2))
for (on_beat, sq, bin_per_beat, off_beat, eq, _, p, v) in d['melody']:
    assert bin_per_beat== _ == 12 # should be quantization bins per beat
    s_ind = int(on_beat * bin_per_beat + sq)
    e_ind = int(off_beat * bin_per_beat + eq)
    p = int(p)
    pr[0, s_ind, p, 0] = e_ind - s_ind
    pr[0, s_ind, p, 1] = v

for (on_beat, sq, bin_per_beat, off_beat, eq, _, p, v) in d['bridge']:
    assert bin_per_beat== _ == 12 # should be quantization bins per beat
    s_ind = int(on_beat * bin_per_beat + sq)
    e_ind = int(off_beat * bin_per_beat + eq)
    p = int(p)
    pr[1, s_ind, p, 0] = e_ind - s_ind
    pr[1, s_ind, p, 1] = v

for (on_beat, sq, bin_per_beat, off_beat, eq, _, p, v) in d['piano']:
    assert bin_per_beat== _ == 12 # should be quantization bins per beat
    s_ind = int(on_beat * bin_per_beat + sq)
    e_ind = int(off_beat * bin_per_beat + eq)
    p = int(p)
    pr[2, s_ind, p, 0] = e_ind - s_ind
    pr[2, s_ind, p, 1] = v

In [19]:
sum(pr[0,64:80,:,0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
from remi_z import MultiTrack, Bar
pos_tot = len(beat) * 12

bars = []
pos_per_bar = 48
for pos_start in range(0, pos_tot, pos_per_bar):
    end_pos = pos_start+pos_per_bar
    t = Bar.from_piano_roll(pr[2, pos_start:end_pos, :, 0], pos_per_bar=pos_per_bar)
    bars.append(t)
    
mt = MultiTrack.from_bars(bars)
mt.to_midi('/home/longshen/work/AccGen/AccGen/temp/test1.mid')

MIDI file successfully written to /home/longshen/work/AccGen/AccGen/temp/test1.mid
